name: Build Linux-UEFI Executable Application (.efi)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-uefi:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código Fuente y Submódulos
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Instalar Compilador Cruzado y Cabeceras UEFI de GNU
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 build-essential gnu-efi

    - name: Compilar Archivos Objeto (C a .o)
      run: |
        # 1. -DCLIBC_NO_LL_HEAP activa tu heap dinámico
        # 2. -I/usr/include/efi mapea el efi.h que le faltaba a linux-uefi.c
        # 3. -Icrosslibc permite usar las cabeceras minimalistas sin conflictos
        x86_64-w64-mingw32-gcc -Wall -Wextra -ffreestanding \
          -fno-stack-protector -mno-red-zone -fPIC -fshort-wchar \
          -DCLIBC_NO_LL_HEAP \
          -I. -Icrosslibc -I/usr/include/efi -I/usr/include/efi/x86_64 \
          -c main.c linux-uefi.c clibc-user-impl.c

    - name: Enlazar Binario Final con Formato .efi
      run: |
        x86_64-w64-mingw32-gcc -nostdlib -shared \
          -Wl,--subsystem,10 -Wl,-e efi_main \
          main.o linux-uefi.o clibc-user-impl.o \
          -o load_elf_binary.efi

    - name: Guardar Artefacto Ejecutable (.efi)
      uses: actions/upload-artifact@v4
      with:
        name: uefi-loader-binary
        path: load_elf_binary.efi
